name: 'Streamdeck cli pack'
description: 'Packs a StreamDeck plugin using the Streamdeck cli tool'
author: 'Neil Enns'

# Define your inputs here.
inputs:
  path:
    description: 'The path to the plugin to pack. Required.'
    required: true

  outputPath:
    description:
      'The path to save the packed plugin to. Optional. If omitted the plugin is
      saved to the working directory.'
    required: false

  force:
    description: 'If true, overwites a package if it exists.'
    default: false
    required: false

  version:
    description:
      'The version for the plugin. Optional. If omitted the version in the
      manifest is used.'
    required: false

runs:
  using: node20
  main: dist/index.js
