name: 'Streamdeck cli pack'
description: 'Packs a StreamDeck plugin using the Streamdeck cli tool'
author: 'Neil Enns'
branding:
  icon: 'package'
  color: 'blue'

# Define your inputs here.
inputs:
  path:
    description:
      'The path to the plugin to pack. Optional. If omitted the first directory
      in the working directory ending in .sdPlugin is used.'
    required: false

  outputPath:
    description:
      'The path to save the packed plugin to. Optional. If omitted the plugin is
      saved to the working directory.'
    required: false

  force:
    description: 'If true, overwites a package if it exists.'
    default: false
    required: false

  version:
    description:
      'The version for the plugin. Optional. If omitted the version tag for the
      GitHub release is used. If no version tag is available the run number is
      used.'
    required: false

  dryRun:
    description: 'If true, generates a report without creating a package.'
    default: false
    required: false

  forceUpdateCheck:
    description:
      'If true, forces an update check for new validation rules. Cannot be used
      in conjunction with noUpdateCheck.'
    default: false
    required: false

  noUpdateCheck:
    description:
      'If true, prevents an update check of new validation rules. Cannot be used
      in conjunction with forceUpdateCheck.'
    default: false
    required: false

runs:
  using: node20
  main: dist/index.js
